import { Movie } from '@/types/movie';

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    overview:
      'Nükleer silahın yaratıcısı J. Robert Oppenheimer\'ın hayatını ve Manhattan Projesi\'ni anlatan destansı bir biyografi filmi.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    releaseYear: 2023,
    duration: 180,
    genres: ['Drama', 'Thriller'],
    mediaType: 'movie',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    language: 'English',
    country: 'USA',
    rating: 8.9,
    userRating: 5,
    isFavorite: true,
    watchStatus: 'watched',
    cinemaLocation: {
      name: 'CinemaximumCevahir',
      address: 'Büyükdere Cd., İstanbul',
      latitude: 41.0682,
      longitude: 29.0103,
    },
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: '2',
    title: 'Dün Gece Seni Düşündüm',
    originalTitle: 'Past Lives',
    overview:
      'Çocukluk aşkları yirmi yıl sonra yeniden buluşan iki Koreli göçmenin hikayesini anlatan büyüleyici bir aşk filmi.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/k3waqVXSnäITOSjXFfFjEjHYkHs.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    releaseYear: 2023,
    duration: 106,
    genres: ['Drama', 'Romance'],
    mediaType: 'movie',
    director: 'Celine Song',
    cast: ['Greta Lee', 'Teo Yoo', 'John Magaro'],
    language: 'Korean',
    country: 'South Korea',
    rating: 7.9,
    isFavorite: false,
    watchStatus: 'plan_to_watch',
    createdAt: '2024-01-02T00:00:00.000Z',
    updatedAt: '2024-01-02T00:00:00.000Z',
  },
  {
    id: '3',
    title: 'Breaking Bad',
    originalTitle: 'Breaking Bad',
    overview:
      'Kanser teşhisi alan bir kimya öğretmeninin uyuşturucu imparatorluğu kurmak için suç dünyasına adım attığını anlatan efsanevi dizi.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    releaseYear: 2008,
    duration: 62, // episodes
    genres: ['Crime', 'Drama', 'Thriller'],
    mediaType: 'series',
    director: 'Vince Gilligan',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn', 'Dean Norris'],
    language: 'English',
    country: 'USA',
    rating: 9.5,
    userRating: 5,
    isFavorite: true,
    watchStatus: 'watched',
    createdAt: '2024-01-03T00:00:00.000Z',
    updatedAt: '2024-01-03T00:00:00.000Z',
  },
  {
    id: '4',
    title: 'Barbie',
    originalTitle: 'Barbie',
    overview:
      'Barbie, Barbieland\'dan kovularak gerçek dünyaya adım atar ve orada kendisi hakkında büyük bir gizemi keşfeder.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIjxynSaOum.jpg',
    releaseYear: 2023,
    duration: 114,
    genres: ['Comedy', 'Fantasy', 'Adventure'],
    mediaType: 'movie',
    director: 'Greta Gerwig',
    cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera'],
    language: 'English',
    country: 'USA',
    rating: 7.0,
    userRating: 4,
    isFavorite: false,
    watchStatus: 'watched',
    createdAt: '2024-01-04T00:00:00.000Z',
    updatedAt: '2024-01-04T00:00:00.000Z',
  },
  {
    id: '5',
    title: 'The Last of Us',
    originalTitle: 'The Last of Us',
    overview:
      'Mantar salgınının yıkıma uğrattığı bir dünyada, savaşta sertleşmiş bir adam, hayatta kalmak için bağışıklığa sahip genç bir kız için umulmadık bir bağ kurar.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9Hr68tZFLFJ11pKB0oNp7EG8PMO.jpg',
    releaseYear: 2023,
    duration: 9,
    genres: ['Drama', 'Action', 'Sci-Fi'],
    mediaType: 'series',
    director: 'Craig Mazin',
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Gabriel Luna'],
    language: 'English',
    country: 'USA',
    rating: 8.8,
    userRating: 5,
    isFavorite: true,
    watchStatus: 'watching',
    cinemaLocation: {
      name: 'IMAX İstanbul',
      address: 'Levent, İstanbul',
      latitude: 41.0822,
      longitude: 29.0137,
    },
    createdAt: '2024-01-05T00:00:00.000Z',
    updatedAt: '2024-01-05T00:00:00.000Z',
  },
  {
    id: '6',
    title: 'Inception',
    originalTitle: 'Inception',
    overview:
      'Rüya hırsızı Dom Cobb\'un, birisinin zihnine fikir yerleştirme operasyonunu anlatan zihin bükümlü bir gerilim şaheseri.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    releaseYear: 2010,
    duration: 148,
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    mediaType: 'movie',
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    language: 'English',
    country: 'USA',
    rating: 8.8,
    isFavorite: false,
    watchStatus: 'plan_to_watch',
    createdAt: '2024-01-06T00:00:00.000Z',
    updatedAt: '2024-01-06T00:00:00.000Z',
  },
];

export const ALL_GENRES = [
  'Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
  'Documentary', 'Drama', 'Fantasy', 'Horror', 'Mystery',
  'Romance', 'Sci-Fi', 'Thriller', 'Western',
] as const;